FROM golang:1.25.3-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/fms ./FMS/Delivery

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/fms /usr/local/bin/fms
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/fms"]